openapi: 3.2.0
info:
  title: Harbor Health API
  description: These APIs provide services for manipulating Harbor project.
  version: '2.0'
servers:
- url: http://localhost/api/v2.0
- url: https://localhost/api/v2.0
security:
- basic: []
- {}
tags:
- name: Health
paths:
  /health:
    get:
      summary: Check the status of Harbor components
      description: Check the status of Harbor components. This path does not require authentication.
      tags:
      - Health
      operationId: getHealth
      parameters:
      - $ref: '#/components/parameters/requestId'
      responses:
        '200':
          description: The health status of Harbor components
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OverallHealthStatus'
        '500':
          $ref: '#/components/responses/500'
components:
  schemas:
    Errors:
      description: The error array that describe the errors got during the handling of request
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    ComponentHealthStatus:
      type: object
      description: The health status of component
      properties:
        name:
          type: string
          description: The component name
        status:
          type: string
          description: The health status of component. Is either "healthy" or "unhealthy".
        error:
          type: string
          description: (optional) The error message when the status is "unhealthy"
    OverallHealthStatus:
      type: object
      description: The system health status
      properties:
        status:
          type: string
          description: The overall health status. It is "healthy" only when all the components' status are "healthy"
        components:
          type: array
          items:
            $ref: '#/components/schemas/ComponentHealthStatus'
    Error:
      description: a model for all the error response coming from harbor
      type: object
      properties:
        code:
          type: string
          description: The error code
        message:
          type: string
          description: The error message
      example:
        code: NOT_FOUND
        message: artifact library/hello-world:latest not found
  parameters:
    requestId:
      name: X-Request-Id
      description: An unique ID for the request
      in: header
      required: false
      schema:
        type: string
        minLength: 1
  responses:
    '500':
      description: Internal server error. Inspect the `errors` array in the response body for details.
      headers:
        X-Request-Id:
          description: The ID of the corresponding request for the response
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
  securitySchemes:
    basic:
      type: http
      scheme: basic
