openapi: 3.2.0
info:
  title: Harbor Systeminfo API
  description: These APIs provide services for manipulating Harbor project.
  version: '2.0'
servers:
- url: http://localhost/api/v2.0
- url: https://localhost/api/v2.0
security:
- basic: []
- {}
tags:
- name: System Info
paths:
  /systeminfo:
    get:
      summary: Get general system info
      operationId: getSystemInfo
      description: This API is for retrieving general system info, this can be called by anonymous request. Some attributes will be omitted in the response when this API is called by anonymous request.
      tags:
      - System Info
      parameters:
      - $ref: '#/components/parameters/requestId'
      responses:
        '200':
          description: Get general info successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralInfo'
        '500':
          $ref: '#/components/responses/500'
  /systeminfo/volumes:
    get:
      summary: Get system volume info (total/free size)
      operationId: getVolumes
      description: This endpoint is for retrieving system volume info that only provides for admin user. Note that the response only reflects the storage status of local disk.
      tags:
      - System Info
      parameters:
      - $ref: '#/components/parameters/requestId'
      responses:
        '200':
          description: Get system volumes successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemInfo'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  /systeminfo/getcert:
    get:
      summary: Get default root certificate
      operationId: getCert
      description: This endpoint is for downloading a default root certificate.
      tags:
      - System Info
      parameters:
      - $ref: '#/components/parameters/requestId'
      responses:
        '200':
          description: Get default root certificate successfully.
          headers:
            Content-Disposition:
              description: To set the filename of the downloaded file.
              schema:
                type: string
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: Not found the default root certificate.
        '500':
          $ref: '#/components/responses/500'
components:
  schemas:
    Errors:
      description: The error array that describe the errors got during the handling of request
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    SystemInfo:
      type: object
      properties:
        storage:
          type: array
          description: The storage of system.
          items:
            $ref: '#/components/schemas/Storage'
    GeneralInfo:
      type: object
      properties:
        banner_message:
          type:
          - string
          - 'null'
          x-omitempty: true
          description: The banner message for the UI. It is the stringified result of the banner message object.
          example: '{"closable":true,"message":"your banner message content","type":"warning","fromDate":"06/19/2023","toDate":"06/21/2023"}'
        current_time:
          type:
          - string
          - 'null'
          format: date-time
          x-omitempty: true
          description: The current time of the server.
        registry_url:
          type:
          - string
          - 'null'
          x-omitempty: true
          description: The url of registry against which the docker command should be issued.
        external_url:
          type:
          - string
          - 'null'
          x-omitempty: true
          description: The external URL of Harbor, with protocol.
        auth_mode:
          type:
          - string
          - 'null'
          x-omitempty: true
          description: The auth mode of current Harbor instance.
        primary_auth_mode:
          type:
          - boolean
          - 'null'
          x-omitempty: true
          description: The flag to indicate whether the current auth mode should consider as a primary one.
        project_creation_restriction:
          type:
          - string
          - 'null'
          x-omitempty: true
          description: Indicate who can create projects, it could be 'adminonly' or 'everyone'.
        self_registration:
          type:
          - boolean
          - 'null'
          x-omitempty: true
          description: Indicate whether the Harbor instance enable user to register himself.
        has_ca_root:
          type:
          - boolean
          - 'null'
          x-omitempty: true
          description: Indicate whether there is a ca root cert file ready for download in the file system.
        harbor_version:
          type:
          - string
          - 'null'
          x-omitempty: true
          description: The build version of Harbor.
        registry_storage_provider_name:
          type:
          - string
          - 'null'
          x-omitempty: true
          description: The storage provider's name of Harbor registry
        read_only:
          type:
          - boolean
          - 'null'
          x-omitempty: true
          description: The flag to indicate whether Harbor is in readonly mode.
        notification_enable:
          type:
          - boolean
          - 'null'
          x-omitempty: true
          description: The flag to indicate whether notification mechanism is enabled on Harbor instance.
        authproxy_settings:
          description: The setting of auth proxy this is only available when Harbor relies on authproxy for authentication.
          x-omitempty: true
          $ref: '#/components/schemas/AuthproxySetting'
        oidc_provider_name:
          type:
          - string
          - 'null'
          x-omitempty: true
          description: The OIDC provider name, empty if current auth is not OIDC_auth or OIDC provider is not configured.
    Storage:
      type: object
      properties:
        total:
          type: integer
          format: uint64
          description: Total volume size.
        free:
          type: integer
          format: uint64
          description: Free volume size.
    Error:
      description: a model for all the error response coming from harbor
      type: object
      properties:
        code:
          type: string
          description: The error code
        message:
          type: string
          description: The error message
      example:
        code: NOT_FOUND
        message: artifact library/hello-world:latest not found
    AuthproxySetting:
      type: object
      properties:
        endpoint:
          type: string
          description: The fully qualified URI of login endpoint of authproxy, such as 'https://192.168.1.2:8443/login'
        tokenreivew_endpoint:
          type: string
          description: The fully qualified URI of token review endpoint of authproxy, such as 'https://192.168.1.2:8443/tokenreview'
        skip_search:
          type: boolean
          description: The flag to determine whether Harbor can skip search the user/group when adding him as a member.
        verify_cert:
          type: boolean
          description: The flag to determine whether Harbor should verify the certificate when connecting to the auth proxy.
        server_certificate:
          type: string
          description: The certificate to be pinned when connecting auth proxy.
  parameters:
    requestId:
      name: X-Request-Id
      description: An unique ID for the request
      in: header
      required: false
      schema:
        type: string
        minLength: 1
  responses:
    '500':
      description: Internal server error. Inspect the `errors` array in the response body for details.
      headers:
        X-Request-Id:
          description: The ID of the corresponding request for the response
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    '404':
      description: Not found. The requested resource does not exist.
      headers:
        X-Request-Id:
          description: The ID of the corresponding request for the response
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    '401':
      description: Unauthorized. Authentication is required to access this resource.
      headers:
        X-Request-Id:
          description: The ID of the corresponding request for the response
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    '403':
      description: Forbidden. The caller does not have sufficient permission to perform the requested operation.
      headers:
        X-Request-Id:
          description: The ID of the corresponding request for the response
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
  securitySchemes:
    basic:
      type: http
      scheme: basic
